import Link from "next/link";

export const metadata = {
  title: "Privacy Policy | Nova Taxi",
  description: "Privacy policy of Nova Taxi – Information about how we handle your personal data.",
};

export default function PrivacyPolicyPage() {
  return (
    <section className="section-padding">
      <div className="container max-w-3xl space-y-8">
        <div className="space-y-4">
          <p className="text-xs uppercase tracking-[0.4em] text-gray-400">
            Legal
          </p>
          <h1 className="text-3xl md:text-4xl font-semibold text-white">
            Privacy Policy
          </h1>
        </div>

        <div className="space-y-6 text-gray-300">
          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-white">1. Responsible Party</h2>
            <p>
              Responsible for data processing on this website is:
            </p>
            <address className="not-italic mt-2">
              <p>Nova Taxi</p>
              <p>Türlihof 4</p>
              <p>6414 Oberarth, Switzerland</p>
              <p>Email: <a href="mailto:info@nova-taxi.com" className="text-nova-gold hover:text-nova-gold-soft">info@nova-taxi.com</a></p>
            </address>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-white">2. Data Collection and Processing</h2>
            <p className="text-sm">
              When visiting our website, certain data is automatically collected that your 
              browser transmits to our server (so-called server log files). These include: 
              browser type and version, operating system used, referrer URL (previously 
              visited page), hostname of the accessing computer (IP address), time of 
              server request.
            </p>
            <p className="text-sm mt-2">
              This data is not combined with other data sources and is used exclusively 
              for statistical evaluation to improve our services.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-white">3. Contact</h2>
            <p className="text-sm">
              When you contact us by phone, email or WhatsApp, the data you provide 
              (e.g. name, phone number, email address, message) is stored to process 
              your inquiry and handle any follow-up questions. This data will not be 
              shared without your consent.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-white">4. Booking Data</h2>
            <p className="text-sm">
              When booking a ride, we collect the following data:
            </p>
            <ul className="text-sm list-disc list-inside mt-2 space-y-1">
              <li>Name and contact details (phone number, email)</li>
              <li>Pickup address and destination address</li>
              <li>Date and time of the ride</li>
              <li>Number of passengers</li>
              <li>Special requests (e.g. child seat)</li>
            </ul>
            <p className="text-sm mt-2">
              This data is used exclusively to carry out the booked service and is 
              stored after completion of the ride in accordance with legal retention periods.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-white">5. Google Analytics</h2>
            <p className="text-sm">
              This website uses Google Analytics, a web analytics service provided by 
              Google LLC. Google Analytics uses cookies that enable analysis of your 
              use of the website. The information generated by the cookie about your 
              use of this website is usually transmitted to a Google server in the USA 
              and stored there.
            </p>
            <p className="text-sm mt-2">
              We have activated IP anonymization so that your IP address is truncated 
              by Google within member states of the European Union or in other 
              contracting states of the Agreement on the European Economic Area.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-white">6. Cookies</h2>
            <p className="text-sm">
              Our website uses cookies. Cookies are small text files that are stored 
              on your device and that your browser saves. Cookies do not cause any 
              damage to your device and do not contain viruses.
            </p>
            <p className="text-sm mt-2">
              You can configure your browser to inform you about the setting of cookies 
              and only allow cookies in individual cases, exclude the acceptance of 
              cookies for certain cases or in general, and activate the automatic 
              deletion of cookies when closing the browser.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-white">7. Your Rights</h2>
            <p className="text-sm">
              You have the right at any time to:
            </p>
            <ul className="text-sm list-disc list-inside mt-2 space-y-1">
              <li>Request information about your data stored with us</li>
              <li>Request correction of incorrect data</li>
              <li>Request deletion of your data</li>
              <li>Request restriction of processing</li>
              <li>Object to the processing of your data</li>
              <li>Receive your data in a transferable format</li>
            </ul>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-white">8. Data Security</h2>
            <p className="text-sm">
              We use technical and organizational security measures to protect your 
              data against accidental or intentional manipulation, loss, destruction 
              or access by unauthorized persons. Our security measures are continuously 
              improved in line with technological developments.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-white">9. Changes to the Privacy Policy</h2>
            <p className="text-sm">
              We reserve the right to adapt this privacy policy to ensure it always 
              complies with current legal requirements or to implement changes to our 
              services. The new privacy policy will then apply to your next visit.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-semibold text-white">10. Contact for Questions</h2>
            <p className="text-sm">
              If you have any questions about data protection, you can contact us at any time:
            </p>
            <p className="mt-2">
              Email: <a href="mailto:info@nova-taxi.com" className="text-nova-gold hover:text-nova-gold-soft">info@nova-taxi.com</a>
            </p>
            <p>
              Phone: <a href="tel:+41766113131" className="text-nova-gold hover:text-nova-gold-soft">+41 76 611 31 31</a>
            </p>
          </div>

          <p className="text-xs text-gray-500 pt-4">
            Last updated: February 2025
          </p>
        </div>

        <nav className="border-t border-white/10 pt-6">
          <div className="flex flex-wrap gap-4 text-sm">
            <Link href="/en/impressum" className="text-gray-300 hover:text-nova-gold transition-colors">
              → Imprint
            </Link>
            <Link href="/en/agb" className="text-gray-300 hover:text-nova-gold transition-colors">
              → Terms & Conditions
            </Link>
            <Link href="/en/kontakt" className="text-gray-300 hover:text-nova-gold transition-colors">
              → Contact
            </Link>
          </div>
        </nav>
      </div>
    </section>
  );
}
